### ISSUE TITLE
No screen on switch.

### ISSUE THREAD

**Issue by zqpvr** [zqpvr/L4T-Debian-12#6]
How do you get the screen to show up as It boots and fan does work for me but I can't seem to get the screen to show up.
@RSC-Games

**Comment by RSC-Games** [comment]
This is a side effect of the failure of LightDM to start. To start it, you need to type `switch`, press enter, `switch`, press enter, and then type `/etc/X11/Xsession` and press enter.

**Comment by RSC-Games** [comment]
The cause of this is the reason for #1

**Comment by RSC-Games** [comment]
Well it worked for me.
